import type { Product } from '../src/types';

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Fresh Tomatoes',
    description: 'Farm fresh red tomatoes',
    price: 45,
    mrp: 60,
    category: 'Vegetables',
    department: 'Fresh Produce',
    rawSellingPrice: 45,
  },
  {
    id: 'p2',
    name: 'Aashirvaad Atta (5kg)',
    description: 'Whole wheat flour',
    price: 240,
    mrp: 285,
    category: 'Staples',
    department: 'Groceries',
    rawSellingPrice: 240,
  },
  {
    id: 'p3',
    name: 'Amul Gold Milk (500ml)',
    description: 'Full cream milk',
    price: 32,
    mrp: 32,
    category: 'Dairy',
    department: 'Dairy & Breakfast',
    rawSellingPrice: 32,
  },
  {
    id: 'p4',
    name: 'Tata Salt (1kg)',
    description: 'Iodized salt',
    price: 25,
    mrp: 28,
    category: 'Staples',
    department: 'Groceries',
    rawSellingPrice: 25,
  },
  {
    id: 'p5',
    name: 'Onions (1kg)',
    description: 'Fresh onions',
    price: 30,
    mrp: 40,
    category: 'Vegetables',
    department: 'Fresh Produce',
    rawSellingPrice: 30,
  },
];
